from config import SUDO_USERS, HELP_PIC

from pyrogram import Client, filters
from pyrogram.types import Message

hl = "."

EXTRA_TEXT = f"""
**ʙᴏᴛ ᴄᴏᴍᴍᴀɴᴅꜱ** 

• `{hl}ping` » ᴛᴏ ᴄʜᴇᴄᴋ ʙᴏᴛ ᴘɪɴɢ ᴀɴᴅ ᴜᴘᴛɪᴍᴇ....

• `{hl}restart` » ᴛᴏ ʀᴇꜱᴛᴀʀᴛ ᴛʜᴇ ʙᴏᴛ....

• `{hl}instantboot` » ɢɪᴠᴇ ᴀ ɪɴꜱᴛᴀɴᴛ/ᴄʜᴀʀɢᴇ ʙᴏᴏᴛ ᴛᴏ ʏᴏᴜʀ ᴅᴇᴘʟᴏʏᴍᴇɴᴛ....

• `{hl}alive` » ᴛᴏ ᴄʜᴇᴄᴋ ʙᴏᴛ ᴀʟɪᴠᴇ ᴏʀ ɴᴏᴛ...

• `{hl}repo` » ᴛᴏ ɢᴇᴛ ʙᴏᴛ ʀᴇᴘᴏ...

• `{hl}id` » ᴛᴏ ɢᴇᴛ ᴄʜᴀᴛ ᴀɴᴅ ʀᴇᴘʟʏᴇᴅ ᴜꜱᴇʀ'ꜱ ᴜꜱᴇʀ_ɪᴅ....

• `{hl}addsudo` » ᴛᴏ ᴀᴅᴅ ꜱᴜᴅᴏ....

• `{hl}sudolist` » ᴛᴏ ɢᴇᴛ ꜱᴜᴅᴏ ᴜꜱᴇʀꜱ ʟɪꜱᴛ....

• `{hl}hping` » ᴛᴏ ᴄʜᴇᴄᴋ ʙᴏᴛ'ꜱ ɴᴏɴ ʙᴏᴏꜱᴛᴇᴅ ᴘɪɴɢ ᴀɴᴅ ᴜᴘᴛɪᴍᴇ....

• `{hl}eval` » ᴛᴏ ᴄᴜꜱᴛᴏᴍɪᴢᴇ ᴛʜᴇ ꜰᴜɴᴄᴛɪᴏɴ ᴏꜰ ᴛʜᴇ ᴜꜱᴇʀʙᴏᴛ....

• `{hl}mystats` » ᴛᴏ ᴄʜᴋ ᴄʟɪᴇɴᴛ ꜱᴛᴀᴛꜱ....

• `{hl}bstats` » ᴛᴏ ᴄʜᴇᴄᴋ ʙᴏᴛ ꜱᴛᴀᴛꜱ....

• `{hl}join` » ᴛᴏ ᴊᴏɪɴ ᴄʜᴀᴛ....

• `{hl}leave` » ᴛᴏ ʟᴇᴀᴠᴇ ᴄʜᴀᴛ...
"""

@Client.on_message(filters.user(SUDO_USERS) & filters.command(["helpbot"], ["."]))
async def help(xspam: Client, msg: Message):
       if ".jpg" in HELP_PIC or ".png" in HELP_PIC:
              await xspam.send_photo(msg.chat.id, HELP_PIC, caption=EXTRA_TEXT)
       if ".mp4" in HELP_PIC or ".MP4," in HELP_PIC:
              await xspam.send_video(msg.chat.   id, HELP_PIC, caption=EXTRA_TEXT)
